#!/bin/bash

# Install native dependencies for all available architectures
export available_architectures=(amd64)
export packages=(build-essential dh-make devscripts lintian)
for arch in "${available_architectures[@]}"; do
    dpkg --add-architecture "${arch}"
    packages+=("crossbuild-essential-${arch}")
done

apt update
apt install -y "${packages[@]}"

# Move to temporary directory
export SRC_DIR="${PWD}"
export DST_DIR="${SRC_DIR}/out"
export OUT_DIR="/out"
export WORK_DIR="${OUT_DIR}/src"

mkdir -p "${DST_DIR}"
mkdir -p "${OUT_DIR}"

cp -r "${SRC_DIR}" "${WORK_DIR}"
cd "${WORK_DIR}" || exit

# Build for all available architectures
for arch in "${available_architectures[@]}"; do
    # Install build dependencies
    apt build-dep -y -a "${arch}" .

    # Build package
    debuild -us -uc -i -I -a "${arch}"
done

# Copy output to output directory
cp ${OUT_DIR}/* "${DST_DIR}" || :
