#!/bin/bash

# Build tarball and source package
export PACKAGE="desktop-integrated-webserver-rpm-0.0.1"
export SUFFIX="1.fc34"
export SPEC="desktop-integrated-webserver-rpm.spec"

dnf install -y fedora-packager @development-tools qemu-user-static

rpmdev-setuptree

export TARBALL="${HOME}/rpmbuild/SOURCES/${PACKAGE}.tar.gz"
export DSC="${HOME}/rpmbuild/SRPMS/${PACKAGE}-${SUFFIX}.src.rpm"

tar -cvzf "${TARBALL}" --exclude out --transform "s,^,${PACKAGE}/," .
rpmbuild -bs "${SPEC}"

rpmlint "${DSC}"

mkdir -p out
cp "${TARBALL}" "${DSC}" out || exit 1

# Build chroot
declare -A TARGETS
export TARGETS=(["epel-8"]="x86_64" ["fedora-34"]="x86_64" ["opensuse-tumbleweed"]="x86_64")

for DIST in "${!TARGETS[@]}"; do
    # Build binary package
    for ARCH in ${TARGETS[$DIST]}; do
        mock -r "${DIST}-${ARCH}" "${DSC}" --enable-network

        rm /var/lib/mock/"${DIST}-${ARCH}"/result/*.src.rpm
        rpmlint /var/lib/mock/"${DIST}-${ARCH}"/result/*.rpm

        cp /var/lib/mock/"${DIST}-${ARCH}"/result/*.rpm out || exit 1
        mv out/*.src.rpm "out/${PACKAGE}.src.rpm" || exit 1
    done
done
