---
sdk_path: "/root/Android/Sdk"
repo_url: "https://pojntfx.github.io/hydrapp/hydrapp-example-dudirekta-parcel//apk/stable/repo"
repo_name: Hydrapp F-Droid Repo
repo_description: >-
  Android apps for Hydrapp.
repo_icon: icon.png
repo_keyalias: hydrapp
keystore: keystore.p12
keystorepass: "keypass1234"
keypass: "keypass1234"
keydname: CN=Hydrapp development certificate of Felicitas Pojtinger
apksigner: /usr/bin/apksigner
