---
sdk_path: "/root/Android/Sdk"
repo_url: "https://pojntfx.github.io/hydrapp/hydrapp-example-react-panrpc//apk/main/repo"
repo_name: hydrapp React and panrpc Example (Main) F-Droid Repo
repo_description: >-
  Android apps for hydrapp React and panrpc Example (Main).
repo_icon: icon.png
repo_keyalias: anonymous hydrapp developer
keystore: keystore.p12
keystorepass: "IIhljuLFgW5cZnYg8FLiITYE03LXoE09"
keypass: "7f7y5KxPTUk20GMJa1bpssCg1VIOSOHt"
keydname: CN=Anonymous Hydrapp Developer
apksigner: /usr/bin/apksigner