APT::FTPArchive::Release::Codename "bullseye";
APT::FTPArchive::Release::Origin "Hydrapp APT repo";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Label "Packages for Hydrapp";
APT::FTPArchive::Release::Architectures "amd64 source";
APT::FTPArchive::Release::Suite "bullseye";
