APT::FTPArchive::Release::Codename "sid";
APT::FTPArchive::Release::Origin "Hydrapp APT repo";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Label "Packages for Hydrapp";
APT::FTPArchive::Release::Architectures "amd64 i386 armel armhf arm64 ppc64el source";
APT::FTPArchive::Release::Suite "sid";
