name: hydrapp CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-oci-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        target:
          - src: hydrapp/pkg/builders/apk
            image: ghcr.io/pojntfx/hydrapp-build-apk
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/deb
            image: ghcr.io/pojntfx/hydrapp-build-deb
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/dmg
            image: ghcr.io/pojntfx/hydrapp-build-dmg
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/flatpak
            image: ghcr.io/pojntfx/hydrapp-build-flatpak
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/msi
            image: ghcr.io/pojntfx/hydrapp-build-msi
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/rpm
            image: ghcr.io/pojntfx/hydrapp-build-rpm
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/binaries
            image: ghcr.io/pojntfx/hydrapp-build-binaries
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/tests
            image: ghcr.io/pojntfx/hydrapp-build-tests
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le
          - src: hydrapp/pkg/builders/docs
            image: ghcr.io/pojntfx/hydrapp-build-docs
            arch: "linux/amd64" # linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/s390x,linux/mips64le,linux/ppc64le

    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.target.image }}
          tags: type=semver,pattern={{version}}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.target.src }}
          file: ${{ matrix.target.src }}/Dockerfile
          platforms: ${{ matrix.target.arch }}
          push: false
          tags: ${{ matrix.target.image }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push pre-release image to registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.target.src }}
          file: ${{ matrix.target.src }}/Dockerfile
          platforms: ${{ matrix.target.arch }}
          push: true
          tags: ${{ matrix.target.image }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push release image to registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.target.src }}
          file: ${{ matrix.target.src }}/Dockerfile
          platforms: ${{ matrix.target.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build-oci-images
    strategy:
      matrix:
        target:
          # com.pojtinger.felicitas.hydrapp.example.vanillajs.forms
          - id: hydrapp-apk.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: deb|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-deb.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-dmg.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-flatpak.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|dmg|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-msi.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|flatpak|dmg|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-rpm.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|flatpak|dmg|msi|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-binaries.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|flatpak|dmg|msi|rpm|tests
            tag: main
            dst: out/*
          - id: hydrapp-tests.hydrapp-example-vanillajs-forms
            src: .
            pkg: hydrapp-example-vanillajs-forms
            exclude: apk|deb|flatpak|dmg|msi|rpm|binaries
            tag: main
            dst: out/*

          # com.pojtinger.felicitas.hydrapp.example.vanillajs.rest
          - id: hydrapp-apk.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: deb|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-deb.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-dmg.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-flatpak.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|dmg|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-msi.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|flatpak|dmg|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-rpm.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|flatpak|dmg|msi|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-binaries.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|flatpak|dmg|msi|rpm|tests
            tag: main
            dst: out/*
          - id: hydrapp-tests.hydrapp-example-vanillajs-rest
            src: .
            pkg: hydrapp-example-vanillajs-rest
            exclude: apk|deb|flatpak|dmg|msi|rpm|binaries
            tag: main
            dst: out/*

          # com.pojtinger.felicitas.hydrapp.example.react.panrpc
          - id: hydrapp-apk.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: deb|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-deb.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|dmg|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-dmg.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|flatpak|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-flatpak.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|dmg|msi|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-msi.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|flatpak|dmg|rpm|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-rpm.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|flatpak|dmg|msi|binaries|tests
            tag: main
            dst: out/*
          - id: hydrapp-binaries.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|flatpak|dmg|msi|rpm|tests
            tag: main
            dst: out/*
          - id: hydrapp-tests.hydrapp-example-react-panrpc
            src: .
            pkg: hydrapp-example-react-panrpc
            exclude: apk|deb|flatpak|dmg|msi|rpm|binaries
            tag: main
            dst: out/*

    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build hydrapp with hydrun
        working-directory: .
        run: hydrun -o golang:bookworm "./Hydrunfile go hydrapp"
      - name: Fix permissions for output
        run: sudo chown -R $USER .
      - name: Install hydrapp
        working-directory: .
        run: sudo install -D -m 0755 out/hydrapp.linux-x86_64 /usr/local/bin/hydrapp
      - name: Remove hydrapp build output
        working-directory: .
        run: rm -rf out
      - name: Setup Java/APK keystore
        working-directory: .
        env:
          JAVA_KEYSTORE: ${{ secrets.JAVA_KEYSTORE }}
        run: echo "${JAVA_KEYSTORE}" | base64 -d >'/tmp/keystore.jks'
      - name: Setup PGP key
        working-directory: .
        env:
          PGP_KEY: ${{ secrets.PGP_KEY }}
        run: echo "${PGP_KEY}" | base64 -d >'/tmp/pgp.asc'
      - name: Build with hydrapp
        working-directory: ${{ matrix.target.src }}
        env:
          HYDRAPP_JAVA_KEYSTORE: /tmp/keystore.jks
          HYDRAPP_JAVA_KEYSTORE_PASSWORD: ${{ secrets.JAVA_KEYSTORE_PASSWORD }}
          HYDRAPP_JAVA_CERTIFICATE_PASSWORD: ${{ secrets.JAVA_CERTIFICATE_PASSWORD }}

          HYDRAPP_PGP_KEY: /tmp/pgp.asc
          HYDRAPP_PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}
          HYDRAPP_PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
        run: |
          hydrapp build --config='./${{ matrix.target.pkg }}/hydrapp.yaml' --exclude='${{ matrix.target.exclude }}' \
            --pull=true --tag='${{ matrix.target.tag }}' \
            --dst="${PWD}/out/${{ matrix.target.pkg }}" --src="${PWD}" \
            --concurrency="$(nproc)"
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.id }}
          path: ${{ matrix.target.dst }}

  publish-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: build-linux
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download output
        uses: actions/download-artifact@v4
        with:
          path: /tmp/out
      - name: Isolate the repositories
        run: |
          mkdir -p /tmp/github-pages
          for dir in /tmp/out/*/; do
            rsync -a "${dir}"/ /tmp/github-pages/
          done

          touch /tmp/github-pages/.nojekyll
      - name: Add index for repositories
        run: |
          sudo apt update
          sudo apt install -y tree

          cd /tmp/github-pages/
          tree --timefmt '%Y-%m-%dT%H:%M:%SZ' -T 'hydrapp Repositories' --du -h -D -H . -o 'index.html'
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/github-pages/
      - name: Publish to GitHub pages
        id: publish
        uses: actions/deploy-pages@v4
